### ISSUE TITLE
Ghost Seeds

### ISSUE THREAD

**Issue by shmup** [calpaterson/thehighseas#1]
I rebooted my VPS three times, and as a result I have three additional seeds. Perhaps they could drop off after x minutes have passed? Er, maybe it just shouldn't list identical IPs. I'm not really sure what a smart solution is.

![screen shot 2013-07-15 at 6 42 59 pm](https://f.cloud.github.com/assets/118710/801418/ef3a35ca-ed9f-11e2-8482-81f7a6525706.png)

**Comment by calpaterson** [comment]
Hey shmup - thanks for reporting this - each peer uses a "peer id" to identify itself, and trackers use it to track them.  Transmission (but not all clients) generate a random peer id when they start up.  If the tracker is down when the torrent (/client) is stopped, then client won't send the "i'm stopped" message to the tracker then the tracker won't remove it from the list of peers.

I can't help listing multiple IPs, I'm afraid - sometimes there are multiple peers on a single IP (if they are behind a NAT, for example).

I've just pushed a change the will remove peers when they haven't been seen for 30 minutes, hopefully this solves this problem!

**Comment by shmup** [comment]
Ah hah, thank you for the explanation. Makes sense.

Your fix will do just fine, and I will close this issue. Thanks!
