### ISSUE TITLE
Leechers not accurate

### ISSUE THREAD

**Issue by shmup** [calpaterson/thehighseas#2]
It always says 0, but I currently have two friends downloading.

**Comment by calpaterson** [comment]
Hey shmup, this seems to work for me, so I have a couple of questions to ask:
1. Are you and your friends all on the same local area network (possibly at a university, or a home router)?
2. Did you change the two settings in config.sh?  (You will almost always have to change THS_HOST)

Thanks for reporting issues!

**Comment by shmup** [comment]
Ah hah, no I left them default. Well, besides changing localhost to 127.0.0.1. What would you possibly change THS_HOST to?

edit: I should just delete the comment, but for historical sake, I'll leave it be. No, I did not read your config.sh comment, which clearly says what to update the THS_HOST to, heh.

**Comment by shmup** [comment]
For the sake of clarifying, even if this might seem obvious to others:

THS_HOST must not start with http://

The config comment initially confused me, since I basically took it as verbatim, heh.

`# If they visit http://foo.com:91 these variables should match that`

I literally split it up as is: http://foo.com and 91, instead of foo.com and 91.

Anyways, thanks again!
